Have changed paths in basis_functions.py to use acrg_config.paths. Two test in test_acrg_basis_functions.py have failed but the error is AttributeError: module 'acrg_name.basis_functions' has no attribute 'basis_blocks'. Have updated flux.py so it no longer defaults to the folder /data/shared/. It now uses acrg_config.paths to find the data folder.
Former-commit-id: 61ebf18af7a1207d77e3558caafc4631eefa4227